twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        menu: '@App\Repository\MenuRepository'
        pageTitle: '%page_title%'

when@test:
    twig:
        strict_variables: true
